# Generated by Django 5.2.14 on 2026-05-31 07:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InterviewSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_date", models.DateTimeField(auto_now_add=True)),
                ("messages", models.JSONField(default=list)),
                ("technical_score", models.IntegerField(blank=True, null=True)),
                ("communication_score", models.IntegerField(blank=True, null=True)),
                ("overall_score", models.IntegerField(blank=True, null=True)),
                ("feedback", models.TextField(blank=True)),
                ("strengths", models.JSONField(default=list)),
                ("improvements", models.JSONField(default=list)),
                ("is_complete", models.BooleanField(default=False)),
                ("resume_text", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-session_date"],
            },
        ),
    ]
